modLoader="javafml"
loaderVersion="[4,)"
license="LGPLv3"
issueTrackerURL="https://github.com/maruohon/malilib/issues"

[[mods]]
modId="malilib"
version="${mod_version}"
displayName="MaLiLib"
updateJSONURL="https://masa.dy.fi/maven/malilib/malilib.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/malilib"
logoFile="assets/malilib/icon.png"
authors="masa"
description="A library mod required by masa's client-side mods"
displayTest="IGNORE_SERVER_VERSION"

[[dependencies.malilib]]
modId="neoforge"
type="required"
versionRange="[21.0,)"
ordering="NONE"
side="CLIENT"

[[dependencies.malilib]]
modId="minecraft"
type="required"
versionRange="[1.21,1.21.1]"
ordering="NONE"
side="CLIENT"

[client]
clientConfigPath="config"

[[mixins]]
config="mixins.malilib.json"

[[mixins]]
config="mixins.malilib.neoforge.json"
